all: intro count histogram vertical
intro: intro.c
	gcc -ansi -pedantic -Wall intro.c -o intro
count: count.c
	gcc -ansi -pedantic -Wall count.c -o count
histogram: histogram.c
	gcc -ansi -pedantic -Wall histogram.c -o histogram
vertical: vertical.c
	gcc -ansi -pedantic -Wall vertical.c -o vertical
