all: temperature name chars sizeof ex1 ex3 ex4 ex5
temperature: temperature.c
	gcc -ansi -pedantic -Wall temperature.c -o temperature
name: name.c
	gcc -ansi -pedantic -Wall name.c -o name
chars: chars.c
	gcc -ansi -pedantic -Wall chars.c -o chars
sizeof: sizeof.c
	gcc -ansi -pedantic -Wall sizeof.c -o sizeof
ex1: ex1.c
	gcc -ansi -pedantic -Wall ex1.c -o ex1
ex3: ex3.c
	gcc -ansi -pedantic -Wall ex3.c -o ex3
ex4: ex4.c
	gcc -ansi -pedantic -Wall ex4.c -o ex4 -lm
ex5: ex5.c
	gcc -ansi -pedantic -Wall ex5.c -o ex5 
