all: ex1 ex3 ex4 ex5 ex6
ex1: ex1.c
	gcc -ansi -pedantic -pedantic ex1.c -o ex1
ex3: ex3.c
	gcc -ansi -pedantic -pedantic ex3.c -o ex3
ex4: ex4.c
	gcc -ansi -pedantic -pedantic ex4.c -o ex4 -lm
ex5: ex5.c
	gcc -ansi -pedantic -pedantic ex5.c -o ex5
ex6: ex6.c
	gcc -ansi -pedantic -pedantic ex6.c -o ex6 -lm
