all: intro printfAboveAverage histogram sieve
intro: intro.c
	gcc -ansi -pedantic -Wall intro.c -o intro
printfAboveAverage: printfAboveAverage.c
	gcc -ansi -pedantic -Wall printfAboveAverage.c -o printfAboveAverage
histogram: histogram.c
	gcc -ansi -pedantic -Wall histogram.c -o histogram
sieve: sieve.c
	gcc -ansi -pedantic -Wall sieve.c -o sieve 
