all: temperature factorial chars
temperature: temperature.c
	gcc -ansi -pedantic -g -Wall temperature.c -o temperature
factorial: factorial.c
	gcc -ansi -pedantic -g -Wall factorial.c -o factorial
chars: chars.c
	gcc -ansi -pedantic -g -Wall chars.c -o chars
