all: week2ex1 week2ex3 week2ex4 week2ex5 week2ex6 logic while factorial gcd week3 loop-a series stars
week2ex1: week2ex1.c
	gcc -ansi -pedantic -Wall -g week2ex1.c -o week2ex1
week2ex3: week2ex3.c
	gcc -ansi -pedantic -Wall -g week2ex3.c -o week2ex3
week2ex4: week2ex4.c
	gcc -ansi -pedantic -Wall -g week2ex4.c -o week2ex4 -lm
week2ex5: week2ex5.c
	gcc -ansi -pedantic -Wall -g week2ex5.c -o week2ex5
week2ex6: week2ex6.c
	gcc -ansi -pedantic -Wall -g week2ex6.c -o week2ex6 -lm
logic: logic.c
	gcc -ansi -pedantic -Wall -g logic.c -o logic -lm
while: while.c
	gcc -ansi -pedantic -Wall -g while.c -o while
factorial: factorial.c
	gcc -ansi -pedantic -Wall -g factorial.c -o factorial
gcd: gcd.c
	gcc -ansi -pedantic -Wall -g gcd.c -o gcd
week3: week3.c
	gcc -ansi -pedantic -Wall -g week3.c -o week3
loop-a: loop-a.c
	gcc -ansi -pedantic -Wall -g loop-a.c -o loop-a
series: series.c
	gcc -ansi -pedantic -Wall -g series.c -o series
stars: stars.c
	gcc -ansi -pedantic -Wall -g stars.c -o stars
