all: dics bool max sort average factorial gcd series stars stars1 min reverse size
dics: dics.c
	gcc -ansi -pedantic -Wall dics.c -o dics -lm
bool: bool.c
	gcc -ansi -pedantic -Wall bool.c -o bool
max: max.c
	gcc -ansi -pedantic -Wall max.c -o max
sort: sort.c
	gcc -ansi -pedantic -Wall sort.c -o sort
average: average.c
	gcc -ansi -pedantic -Wall average.c -o average
factorial: factorial.c
	gcc -ansi -pedantic -Wall factorial.c -o factorial
gcd: gcd.c
	gcc -ansi -pedantic -Wall gcd.c -o gcd
series: series.c
	gcc -ansi -pedantic -Wall series.c -o series
stars: stars.c
	gcc -ansi -pedantic -Wall stars.c -o stars
stars1: stars1.c
	gcc -ansi -pedantic -Wall stars1.c -o stars1
min: min.c
	gcc -ansi -pedantic -Wall min.c -o min
reverse: reverse.c
	gcc -ansi -pedantic -Wall reverse.c -o reverse
size: size.c
	gcc -ansi -pedantic -Wall size.c -o size
