all: square-root max-four day-in-week average loops gcd tutorial series stars min palindrome parallelogram triangle
square-root: square-root.c
	gcc -ansi -pedantic -Wall square-root.c -o square-root -lm
max-four: max-four.c
	gcc -ansi -pedantic -Wall max-four.c -o max-four
day-in-week: day-in-week.c
	gcc -ansi -pedantic -Wall day-in-week.c -o day-in-week
average: average.c
	gcc -ansi -pedantic -Wall average.c -o average
loops: loops.c
	gcc -ansi -pedantic -Wall loops.c -o loops
gcd: gcd.c
	gcc -ansi -pedantic -Wall gcd.c -o gcd
tutorial: tutorial.c
	gcc -ansi -pedantic -Wall tutorial.c -o tutorial
series: series.c
	gcc -ansi -pedantic -Wall series.c -o series
stars: stars.c
	gcc -ansi -pedantic -Wall stars.c -o stars
min: min.c
	gcc -ansi -pedantic -Wall min.c -o min
palindrome: palindrome.c
	gcc -ansi -pedantic -Wall palindrome.c -o palindrome
parallelogram: parallelogram.c
	gcc -ansi -pedantic -Wall parallelogram.c -o parallelogram
triangle: triangle.c
	gcc -ansi -pedantic -Wall triangle.c -o triangle
