all: gcd logic loop-a series stars week3 while min reverse size seven

gcd: gcd.c
	gcc -ansi -pedantic -Wall -g gcd.c -o gcd
logic: logic.c
	gcc -ansi -pedantic -Wall -g logic.c -o logic -lm
loop-a: loop-a.c
	gcc -ansi -pedantic -Wall -g loop-a.c -o loop-a
series: series.c
	gcc -ansi -pedantic -Wall -g series.c -o series
stars: stars.c
	gcc -ansi -pedantic -Wall -g stars.c -o stars
week3: week3.c
	gcc -ansi -pedantic -Wall -g week3.c -o week3 
while: while.c
	gcc -ansi -pedantic -Wall -g while.c -o while
min: min.c
	gcc -ansi -pedantic -Wall -g min.c -o min
reverse: reverse.c
	gcc -ansi -pedantic -Wall -g reverse.c -o reverse
size: size.c
	gcc -ansi -pedantic -Wall -g size.c -o size
seven: seven.c
	gcc -ansi -pedantic -Wall -g seven.c -o seven
