all: introOut week1Out temperature chars sizeOf casting factorial
introOut: intro.c
	gcc -ansi -pedantic -g -Wall intro.c -o introOut
week1Out: week1.c
	gcc -ansi -pedantic -g -Wall week1.c -o week1Out
temperature: temperature.c
	gcc -ansi -pedantic -g -Wall temperature.c -o temperature
chars: chars.c
	gcc -ansi -pedantic -g -Wall chars.c -o chars
sizeOf: sizeOf.c
	gcc -ansi -pedantic -g -Wall sizeOf.c -o sizeOf
casting: casting.c
	gcc -ansi -pedantic -g -Wall casting.c -o casting
factorial: factorial.c
	gcc -ansi -pedantic -Wall -g factorial.c -o factorial
