all: count histogram frequencies square
count: count.c
	gcc -ansi -pedantic -g -Wall count.c -o count
histogram: histogram.c
	gcc -ansi -pedantic -g -Wall histogram.c -o histogram
frequencies: frequencies.c
	gcc -ansi -pedantic -g -Wall frequencies.c -o frequenciesf
square: square.c
	gcc -ansi -pedantic -g -Wall square.c -o square
